from datetime import datetime, timezone
from typing import Dict, List, Optional


def generate_citizen_brief(
    document_title: str,
    client_name: str,
    analysis_data: Dict,
    custom_questions: Optional[List[str]] = None
) -> Dict:
    """
    Generate a structured, professional briefing memo designed for citizen consultation with a legal advocate.
    """
    now_str = datetime.now(timezone.utc).strftime("%d %B %Y")
    risks = analysis_data.get("risks", [])
    missing = analysis_data.get("missing_clauses", [])

    key_issues = [r.get("title", "") for r in risks[:5] if r.get("title")]
    if not key_issues:
        key_issues = ["General contract term review", "Notice period and termination terms clarification"]

    default_questions = [
        "Are the late payment interest rates and penalty terms in this contract legally enforceable in court?",
        "Can the counterparty unilaterally terminate this agreement without assigning valid cause?",
        "Does the dispute resolution clause prevent me from accessing the local consumer forum or civil court?",
        "What specific amendments or addenda should I insist on before signing or agreeing to these terms?"
    ]
    if custom_questions:
        default_questions.extend(custom_questions)

    # Markdown brief construction
    md_lines = [
        "# CITIZEN LEGAL CONSULTATION BRIEF",
        f"**Date:** {now_str}  ",
        f"**Document Analyzed:** {document_title}  ",
        f"**Prepared For:** {client_name}  ",
        "**Purpose:** Pre-consultation summary prepared using Nyaya Rakshak for review with an Advocate  ",
        "\n---\n",
        "## 1. Executive Summary",
        analysis_data.get("summary_citizen", "Document summary not available."),
        "\n## 2. Key Red Flags & Legal Vulnerabilities Identified",
    ]

    for i, r in enumerate(risks, 1):
        md_lines.append(f"### {i}. {r.get('title', 'Risk Item')} ({r.get('severity', 'MEDIUM')})")
        md_lines.append(f"- **Description:** {r.get('description', '')}")
        md_lines.append(f"- **Contract Reference:** {r.get('clause_reference', 'General')}")
        md_lines.append(f"- **Suggested Countermeasure:** {r.get('countermeasure', 'Seek legal advice')}")

    if missing:
        md_lines.append("\n## 3. Absent Protective Clauses (Missing Safeguards)")
        for m in missing:
            md_lines.append(f"- **{m.get('clause_name', '')}**: {m.get('why_needed', '')} *(Suggested: {m.get('suggested_language', '')})*")

    md_lines.append("\n## 4. Key Questions to Ask Your Advocate")
    for q in default_questions:
        md_lines.append(f"- [ ] {q}")

    md_lines.append("\n---\n")
    md_lines.append(
        "**LEGAL DISCLAIMER:** *This brief was generated by Nyaya Rakshak for citizen educational and organizational purposes only. "
        "It does not constitute formal legal counsel, create an attorney-client relationship, or guarantee legal outcomes. "
        "Always consult a qualified advocate enrolled with the State Bar Council.*"
    )

    full_markdown = "\n".join(md_lines)

    return {
        "title": f"Legal Consultation Brief: {document_title}",
        "client_name": client_name,
        "brief_markdown": full_markdown,
        "key_issues": key_issues,
        "questions_for_lawyer": default_questions
    }
