"""initial_production_schema_29_entities

Revision ID: 662f70770138
Revises:
Create Date: 2026-09-14 00:23:53.135024

"""
from typing import Sequence, Union

import sqlalchemy as sa

import app.db.models
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '662f70770138'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legal_aid_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('organization_type', sa.String(length=50), nullable=False),
    sa.Column('jurisdiction', sa.String(length=100), nullable=False),
    sa.Column('contact_phone', sa.String(length=100), nullable=True),
    sa.Column('toll_free_number', sa.String(length=50), nullable=True),
    sa.Column('website_url', sa.String(length=512), nullable=True),
    sa.Column('office_address', sa.Text(), nullable=True),
    sa.Column('services_offered', sa.Text(), nullable=False),
    sa.Column('income_ceiling_inr', sa.Integer(), nullable=False),
    sa.Column('is_free_service', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("organization_type IN ('NALSA', 'SLSA', 'DLSA', 'TLSC', 'TELE_LAW', 'CONSUMER_FORUM', 'CYBER_HELPLINE')", name='ck_legal_aid_org_type'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('legal_aid_resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_legal_aid_resources_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_aid_resources_uuid'), ['uuid'], unique=True)

    op.create_table('legal_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=100), nullable=False),
    sa.Column('jurisdiction', sa.String(length=100), nullable=False),
    sa.Column('authority_level', sa.String(length=50), nullable=False),
    sa.Column('publication_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('official_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("authority_level IN ('PARLIAMENT_ACT', 'STATE_ACT', 'SUPREME_COURT_RULING', 'HIGH_COURT_RULING', 'REGULATORY_RULE')", name='ck_legal_source_authority'),
    sa.CheckConstraint("status IN ('DRAFT', 'ACTIVE', 'AMENDED', 'REPEALED', 'SUPERSEDED')", name='ck_legal_source_status'),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name='ck_legal_source_effective_dates'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('legal_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_legal_sources_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_legal_sources_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_sources_uuid'), ['uuid'], unique=True)

    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_organizations_uuid'), ['uuid'], unique=True)

    op.create_table('consents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('consent_type', sa.String(length=50), nullable=False),
    sa.Column('is_granted', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("consent_type IN ('PII_REDACTION', 'EDUCATIONAL_DISCLAIMER_ACK', 'TERMS_OF_SERVICE', 'DATA_PROCESSING')", name='ck_consent_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consents_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consents_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consents_uuid'), ['uuid'], unique=True)

    op.create_table('legal_source_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legal_source_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.String(length=50), nullable=False),
    sa.Column('amendment_act_reference', sa.String(length=255), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('change_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['legal_source_id'], ['legal_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legal_source_id', 'version_number', name='uq_legal_source_version')
    )
    with op.batch_alter_table('legal_source_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_legal_source_versions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_source_versions_legal_source_id'), ['legal_source_id'], unique=False)

    op.create_table('memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'admin', 'advocate', 'member', 'viewer')", name='ck_membership_role'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_membership_org_user')
    )
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memberships_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_user_id'), ['user_id'], unique=False)

    op.create_table('security_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('request_path', sa.String(length=255), nullable=True),
    sa.Column('payload_sample', sa.Text(), nullable=True),
    sa.Column('remediated', sa.Boolean(), nullable=False),
    sa.CheckConstraint("event_type IN ('PROMPT_INJECTION_ATTEMPT', 'BOLA_IDOR_ATTEMPT', 'MALICIOUS_FILE_SIGNATURE', 'UNAUTHORIZED_EXPORT', 'RATE_LIMIT_EXCEEDED')", name='ck_security_event_type'),
    sa.CheckConstraint("severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')", name='ck_security_event_severity'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('security_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_security_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_events_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_events_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_events_uuid'), ['uuid'], unique=True)

    op.create_table('source_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legal_source_id', sa.Integer(), nullable=False),
    sa.Column('section_number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('key_principles', sa.Text(), nullable=True),
    sa.Column('citizen_guidance', sa.Text(), nullable=True),
    sa.Column('historical_reference', sa.String(length=255), nullable=True),
    sa.Column('embedding', app.db.models.SafeVector(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['legal_source_id'], ['legal_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_documents_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_documents_legal_source_id'), ['legal_source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_documents_section_number'), ['section_number'], unique=False)

    op.create_table('action_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('domain_category', sa.String(length=50), nullable=False),
    sa.Column('items', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("domain_category IN ('TENANCY', 'EMPLOYMENT', 'CONSUMER_DISPUTE', 'GENERAL_CONTRACT')", name='ck_action_plan_category'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('action_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_plans_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_plans_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_plans_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_plans_uuid'), ['uuid'], unique=True)

    op.create_table('claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("category IN ('FACTUAL', 'STATUTORY', 'CONTRACTUAL')", name='ck_claim_category'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claims_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_uuid'), ['uuid'], unique=True)

    op.create_table('comparisons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('base_document_id', sa.Integer(), nullable=False),
    sa.Column('target_document_id', sa.Integer(), nullable=False),
    sa.Column('base_title', sa.String(length=255), nullable=False),
    sa.Column('target_title', sa.String(length=255), nullable=False),
    sa.Column('overall_verdict', sa.Text(), nullable=False),
    sa.Column('net_risk_direction', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("net_risk_direction IN ('TARGET_MORE_HARSH', 'TARGET_MORE_BALANCED', 'IDENTICAL', 'INCONCLUSIVE')", name='ck_comparison_direction'),
    sa.CheckConstraint('base_document_id != target_document_id', name='ck_comparison_distinct_docs'),
    sa.ForeignKeyConstraint(['base_document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comparisons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comparisons_base_document_id'), ['base_document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comparisons_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comparisons_target_document_id'), ['target_document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comparisons_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comparisons_uuid'), ['uuid'], unique=True)

    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_uuid'), ['uuid'], unique=True)

    op.create_table('document_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('section_title', sa.String(length=255), nullable=False),
    sa.Column('section_number', sa.String(length=50), nullable=True),
    sa.Column('parent_section_id', sa.Integer(), nullable=True),
    sa.Column('start_page', sa.Integer(), nullable=False),
    sa.Column('end_page', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_section_id'], ['document_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_sections_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_sections_id'), ['id'], unique=False)

    op.create_table('document_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'version_number', name='uq_doc_version_number')
    )
    with op.batch_alter_table('document_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_versions_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_versions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_versions_uuid'), ['uuid'], unique=True)

    op.create_table('processing_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("job_type IN ('OCR_EXTRACTION', 'PII_SANITIZATION', 'VECTOR_INDEXING', 'DEEP_ANALYSIS')", name='ck_proc_job_type'),
    sa.CheckConstraint("status IN ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED')", name='ck_proc_job_status'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('processing_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processing_jobs_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_jobs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_jobs_uuid'), ['uuid'], unique=True)

    op.create_table('clauses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('clause_identifier', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('clean_text', sa.Text(), nullable=False),
    sa.Column('is_unfair', sa.Boolean(), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('statutory_cross_reference', sa.String(length=255), nullable=True),
    sa.Column('embedding', app.db.models.SafeVector(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("risk_level IN ('LOW', 'MEDIUM', 'HIGH', 'SEVERE', 'CRITICAL')", name='ck_clause_risk_level'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clauses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clauses_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clauses_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clauses_uuid'), ['uuid'], unique=True)

    op.create_table('document_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('clean_text', sa.Text(), nullable=False),
    sa.Column('ocr_confidence', sa.Float(), nullable=False),
    sa.Column('layout_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('ocr_confidence >= 0.0 AND ocr_confidence <= 1.0', name='ck_ocr_confidence_range'),
    sa.CheckConstraint('page_number >= 1', name='ck_page_number_positive'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'page_number', name='uq_doc_page_number')
    )
    with op.batch_alter_table('document_pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_pages_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_pages_id'), ['id'], unique=False)

    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_uuid'), ['uuid'], unique=True)

    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('is_found_in_document', sa.Boolean(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('citation_ids', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_answers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_answers_question_id'), ['question_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_answers_uuid'), ['uuid'], unique=True)

    op.create_table('citations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('document_page_id', sa.Integer(), nullable=True),
    sa.Column('verbatim_quote', sa.Text(), nullable=False),
    sa.Column('page_or_section', sa.String(length=100), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("source_type IN ('STATUTE', 'DOCUMENT_PAGE', 'COURT_CASE')", name='ck_citation_source_type'),
    sa.CheckConstraint('confidence_score >= 0.0 AND confidence_score <= 1.0', name='ck_citation_confidence_score'),
    sa.ForeignKeyConstraint(['document_page_id'], ['document_pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('citations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_citations_document_page_id'), ['document_page_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_citations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_citations_source_document_id'), ['source_document_id'], unique=False)

    op.create_table('clause_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_clause_id', sa.Integer(), nullable=False),
    sa.Column('target_clause_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("relationship_type IN ('SUPERSEDES', 'CONFLICTS_WITH', 'DEPENDS_ON', 'MODIFIES')", name='ck_clause_rel_type'),
    sa.CheckConstraint('source_clause_id != target_clause_id', name='ck_no_self_clause_rel'),
    sa.ForeignKeyConstraint(['source_clause_id'], ['clauses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_clause_id'], ['clauses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clause_relationships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clause_relationships_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clause_relationships_source_clause_id'), ['source_clause_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clause_relationships_target_clause_id'), ['target_clause_id'], unique=False)

    op.create_table('comparison_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comparison_id', sa.Integer(), nullable=False),
    sa.Column('base_clause_id', sa.Integer(), nullable=True),
    sa.Column('target_clause_id', sa.Integer(), nullable=True),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('risk_delta_score', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('suggested_negotiation_question', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("change_type IN ('ADDED', 'REMOVED', 'MODIFIED', 'UNCHANGED')", name='ck_comp_finding_change_type'),
    sa.ForeignKeyConstraint(['base_clause_id'], ['clauses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['comparison_id'], ['comparisons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_clause_id'], ['clauses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comparison_findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comparison_findings_base_clause_id'), ['base_clause_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comparison_findings_comparison_id'), ['comparison_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comparison_findings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comparison_findings_target_clause_id'), ['target_clause_id'], unique=False)

    op.create_table('risk_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('clause_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('financial_exposure_amount', sa.Float(), nullable=True),
    sa.Column('statutory_prohibition_ref', sa.String(length=255), nullable=True),
    sa.Column('recommended_countermeasure', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("severity IN ('LOW', 'MEDIUM', 'HIGH', 'SEVERE', 'CRITICAL')", name='ck_risk_finding_severity'),
    sa.ForeignKeyConstraint(['clause_id'], ['clauses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_findings_clause_id'), ['clause_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_findings_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_findings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_findings_uuid'), ['uuid'], unique=True)

    op.create_table('evidence_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('citation_id', sa.Integer(), nullable=True),
    sa.Column('content_snippet', sa.Text(), nullable=False),
    sa.Column('source_authority', sa.String(length=255), nullable=False),
    sa.Column('source_version_or_date', sa.String(length=100), nullable=True),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['citation_id'], ['citations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_items_citation_id'), ['citation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_items_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_items_uuid'), ['uuid'], unique=True)

    op.create_table('claim_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('evidence_item_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('verified_by', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('SUPPORTED', 'PARTIALLY_SUPPORTED', 'UNSUPPORTED', 'CONFLICTING', 'UNVERIFIED')", name='ck_claim_ver_status'),
    sa.CheckConstraint("verified_by IN ('AI_MODEL', 'HUMAN_ADVOCATE', 'STATUTORY_RULE')", name='ck_claim_ver_by'),
    sa.CheckConstraint('confidence_score >= 0.0 AND confidence_score <= 1.0', name='ck_claim_ver_confidence'),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_item_id'], ['evidence_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('claim_verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claim_verifications_claim_id'), ['claim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claim_verifications_evidence_item_id'), ['evidence_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claim_verifications_id'), ['id'], unique=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=False))
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_uuid'), ['uuid'], unique=True)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('consultation_briefs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
        batch_op.create_index(batch_op.f('ix_consultation_briefs_uuid'), ['uuid'], unique=True)

    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding', app.db.models.SafeVector(), nullable=True))

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('content_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('error_message', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_demo', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
        batch_op.create_index(batch_op.f('ix_documents_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_uuid'), ['uuid'], unique=True)
        batch_op.create_foreign_key(None, 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('is_demo', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
        batch_op.create_index(batch_op.f('ix_users_uuid'), ['uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_uuid'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('is_demo')
        batch_op.drop_column('uuid')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_documents_uuid'))
        batch_op.drop_index(batch_op.f('ix_documents_organization_id'))
        batch_op.drop_index(batch_op.f('ix_documents_content_hash'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_demo')
        batch_op.drop_column('error_message')
        batch_op.drop_column('status')
        batch_op.drop_column('content_hash')
        batch_op.drop_column('organization_id')
        batch_op.drop_column('uuid')

    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.drop_column('embedding')

    with op.batch_alter_table('consultation_briefs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consultation_briefs_uuid'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('uuid')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_audit_logs_uuid'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))
        batch_op.drop_column('uuid')

    with op.batch_alter_table('claim_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claim_verifications_id'))
        batch_op.drop_index(batch_op.f('ix_claim_verifications_evidence_item_id'))
        batch_op.drop_index(batch_op.f('ix_claim_verifications_claim_id'))

    op.drop_table('claim_verifications')
    with op.batch_alter_table('evidence_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_items_uuid'))
        batch_op.drop_index(batch_op.f('ix_evidence_items_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_items_document_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_items_citation_id'))

    op.drop_table('evidence_items')
    with op.batch_alter_table('risk_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_findings_uuid'))
        batch_op.drop_index(batch_op.f('ix_risk_findings_id'))
        batch_op.drop_index(batch_op.f('ix_risk_findings_document_id'))
        batch_op.drop_index(batch_op.f('ix_risk_findings_clause_id'))

    op.drop_table('risk_findings')
    with op.batch_alter_table('comparison_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comparison_findings_target_clause_id'))
        batch_op.drop_index(batch_op.f('ix_comparison_findings_id'))
        batch_op.drop_index(batch_op.f('ix_comparison_findings_comparison_id'))
        batch_op.drop_index(batch_op.f('ix_comparison_findings_base_clause_id'))

    op.drop_table('comparison_findings')
    with op.batch_alter_table('clause_relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clause_relationships_target_clause_id'))
        batch_op.drop_index(batch_op.f('ix_clause_relationships_source_clause_id'))
        batch_op.drop_index(batch_op.f('ix_clause_relationships_id'))

    op.drop_table('clause_relationships')
    with op.batch_alter_table('citations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_citations_source_document_id'))
        batch_op.drop_index(batch_op.f('ix_citations_id'))
        batch_op.drop_index(batch_op.f('ix_citations_document_page_id'))

    op.drop_table('citations')
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_answers_uuid'))
        batch_op.drop_index(batch_op.f('ix_answers_question_id'))
        batch_op.drop_index(batch_op.f('ix_answers_id'))

    op.drop_table('answers')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_uuid'))
        batch_op.drop_index(batch_op.f('ix_questions_user_id'))
        batch_op.drop_index(batch_op.f('ix_questions_id'))
        batch_op.drop_index(batch_op.f('ix_questions_conversation_id'))

    op.drop_table('questions')
    with op.batch_alter_table('document_pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_pages_id'))
        batch_op.drop_index(batch_op.f('ix_document_pages_document_id'))

    op.drop_table('document_pages')
    with op.batch_alter_table('clauses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clauses_uuid'))
        batch_op.drop_index(batch_op.f('ix_clauses_id'))
        batch_op.drop_index(batch_op.f('ix_clauses_document_id'))

    op.drop_table('clauses')
    with op.batch_alter_table('processing_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processing_jobs_uuid'))
        batch_op.drop_index(batch_op.f('ix_processing_jobs_id'))
        batch_op.drop_index(batch_op.f('ix_processing_jobs_document_id'))

    op.drop_table('processing_jobs')
    with op.batch_alter_table('document_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_versions_uuid'))
        batch_op.drop_index(batch_op.f('ix_document_versions_id'))
        batch_op.drop_index(batch_op.f('ix_document_versions_document_id'))

    op.drop_table('document_versions')
    with op.batch_alter_table('document_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_sections_id'))
        batch_op.drop_index(batch_op.f('ix_document_sections_document_id'))

    op.drop_table('document_sections')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_uuid'))
        batch_op.drop_index(batch_op.f('ix_conversations_user_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_document_id'))

    op.drop_table('conversations')
    with op.batch_alter_table('comparisons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comparisons_uuid'))
        batch_op.drop_index(batch_op.f('ix_comparisons_user_id'))
        batch_op.drop_index(batch_op.f('ix_comparisons_target_document_id'))
        batch_op.drop_index(batch_op.f('ix_comparisons_id'))
        batch_op.drop_index(batch_op.f('ix_comparisons_base_document_id'))

    op.drop_table('comparisons')
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claims_uuid'))
        batch_op.drop_index(batch_op.f('ix_claims_user_id'))
        batch_op.drop_index(batch_op.f('ix_claims_id'))
        batch_op.drop_index(batch_op.f('ix_claims_document_id'))

    op.drop_table('claims')
    with op.batch_alter_table('action_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_plans_uuid'))
        batch_op.drop_index(batch_op.f('ix_action_plans_user_id'))
        batch_op.drop_index(batch_op.f('ix_action_plans_id'))
        batch_op.drop_index(batch_op.f('ix_action_plans_document_id'))

    op.drop_table('action_plans')
    with op.batch_alter_table('source_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_documents_section_number'))
        batch_op.drop_index(batch_op.f('ix_source_documents_legal_source_id'))
        batch_op.drop_index(batch_op.f('ix_source_documents_id'))

    op.drop_table('source_documents')
    with op.batch_alter_table('security_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_security_events_uuid'))
        batch_op.drop_index(batch_op.f('ix_security_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_security_events_timestamp'))
        batch_op.drop_index(batch_op.f('ix_security_events_id'))

    op.drop_table('security_events')
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_memberships_organization_id'))
        batch_op.drop_index(batch_op.f('ix_memberships_id'))

    op.drop_table('memberships')
    with op.batch_alter_table('legal_source_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_legal_source_versions_legal_source_id'))
        batch_op.drop_index(batch_op.f('ix_legal_source_versions_id'))

    op.drop_table('legal_source_versions')
    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consents_uuid'))
        batch_op.drop_index(batch_op.f('ix_consents_user_id'))
        batch_op.drop_index(batch_op.f('ix_consents_id'))

    op.drop_table('consents')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_uuid'))
        batch_op.drop_index(batch_op.f('ix_organizations_slug'))
        batch_op.drop_index(batch_op.f('ix_organizations_id'))

    op.drop_table('organizations')
    with op.batch_alter_table('legal_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_legal_sources_uuid'))
        batch_op.drop_index(batch_op.f('ix_legal_sources_id'))
        batch_op.drop_index(batch_op.f('ix_legal_sources_code'))

    op.drop_table('legal_sources')
    with op.batch_alter_table('legal_aid_resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_legal_aid_resources_uuid'))
        batch_op.drop_index(batch_op.f('ix_legal_aid_resources_id'))

    op.drop_table('legal_aid_resources')
    # ### end Alembic commands ###
