from typing import Any, Dict, List, Optional

from pydantic import BaseModel, ConfigDict, Field


class DeterministicCurrency(BaseModel):
    model_config = ConfigDict(extra="forbid")
    currency: str
    amount: float
    raw_text: str


class DeterministicPercentage(BaseModel):
    model_config = ConfigDict(extra="forbid")
    value: float
    frequency: str
    raw_text: str


class DeterministicDuration(BaseModel):
    model_config = ConfigDict(extra="forbid")
    count: int
    unit: str
    days_equivalent: float
    raw_text: str


class DeterministicDate(BaseModel):
    model_config = ConfigDict(extra="forbid")
    date_string: str
    format: str
    raw_text: str


class DeterministicSection(BaseModel):
    model_config = ConfigDict(extra="forbid")
    prefix: str
    number: str
    full_reference: str


class DeterministicFacts(BaseModel):
    model_config = ConfigDict(extra="forbid")
    currencies: List[DeterministicCurrency] = Field(default_factory=list)
    percentages: List[DeterministicPercentage] = Field(default_factory=list)
    durations: List[DeterministicDuration] = Field(default_factory=list)
    dates: List[DeterministicDate] = Field(default_factory=list)
    sections: List[DeterministicSection] = Field(default_factory=list)


class ClauseSemanticInterpretation(BaseModel):
    """
    Rich semantic interpretation generated by AI model and merged with deterministic facts.
    """

    model_config = ConfigDict(extra="forbid")

    parties_affected: List[str] = Field(
        default_factory=list, description="Parties bound or benefited by the clause"
    )
    obligations: List[str] = Field(
        default_factory=list, description="Mandatory duties ('shall', 'must')"
    )
    rights: List[str] = Field(
        default_factory=list, description="Entitlements and options ('may', 'has the right')"
    )
    prohibitions: List[str] = Field(
        default_factory=list, description="Forbidden actions ('shall not', 'prohibited')"
    )
    conditions: List[str] = Field(
        default_factory=list, description="Preconditions or qualifications"
    )
    triggers: List[str] = Field(default_factory=list, description="Events that activate the clause")
    deadlines: List[str] = Field(default_factory=list, description="Timeframes and cutoff dates")
    monetary_values: List[str] = Field(
        default_factory=list, description="Stated payment obligations or deposits"
    )
    penalties: List[str] = Field(
        default_factory=list, description="Liquidated damages or late fee provisions"
    )
    termination_conditions: List[str] = Field(
        default_factory=list, description="Grounds for cancellation or exit"
    )
    jurisdiction: Optional[str] = Field(
        None, description="Court or territorial jurisdiction specified"
    )
    governing_law: Optional[str] = Field(
        None, description="Statutory or state law governing the contract"
    )
    arbitration: Optional[str] = Field(None, description="Arbitration rules and seat specified")
    confidentiality: Optional[str] = Field(
        None, description="Confidentiality and non-disclosure requirements"
    )
    indemnity: Optional[str] = Field(None, description="Indemnification and hold-harmless scope")
    liability: Optional[str] = Field(
        None, description="Limitations, exclusions, or caps on liability"
    )
    intellectual_property: Optional[str] = Field(
        None, description="IP assignment, licenses, or moral rights"
    )
    renewal: Optional[str] = Field(None, description="Automatic renewal or extension mechanism")
    dispute_resolution: Optional[str] = Field(
        None, description="Mediation, conciliation, or court escalation steps"
    )
    privacy_data_terms: Optional[str] = Field(
        None, description="Personal data processing terms under DPDP Act"
    )


class EvidenceLocation(BaseModel):
    model_config = ConfigDict(extra="forbid")
    page_number: int
    char_start: int
    char_end: int
    quote_snippet: str


class StructuredClauseRecord(BaseModel):
    """
    Complete structured record representing a legally meaningful clause.
    """

    model_config = ConfigDict(extra="forbid")

    clause_id: str = Field(..., description="Unique identifier within document (e.g. C-01)")
    section: str = Field(..., description="Section or article heading")
    title: str = Field(..., description="Descriptive title of the covenant")
    page: int = Field(..., ge=1, description="Page number where clause appears")
    clause_type: str = Field(..., description="Specific clause covenant type")
    category: str = Field(
        ..., description="Taxonomy domain category (rental, employment, nda, etc.)"
    )
    original_text: str = Field(..., description="Verbatim raw clause text")
    simplified_explanation: str = Field(
        ..., description="Plain-language 8th-grade citizen explanation"
    )
    evidence_location: EvidenceLocation
    deterministic_facts: DeterministicFacts
    structured_interpretation: ClauseSemanticInterpretation
    extraction_confidence: float = Field(..., ge=0.0, le=1.0)
    interpretation_confidence: float = Field(..., ge=0.0, le=1.0)
    is_unfair: bool = Field(
        False, description="Whether the term is potentially unfair under Indian law"
    )
    risk_level: str = Field("LOW", description="Risk level (LOW, MEDIUM, HIGH, SEVERE, CRITICAL)")
    statutory_cross_reference: Optional[str] = Field(
        None, description="Relevant Indian statute (BNS, CPA, Contract Act, etc.)"
    )

    # Property accessors for direct convenience
    @property
    def parties_affected(self) -> List[str]:
        return self.structured_interpretation.parties_affected

    @property
    def obligations(self) -> List[str]:
        return self.structured_interpretation.obligations

    @property
    def rights(self) -> List[str]:
        return self.structured_interpretation.rights

    @property
    def prohibitions(self) -> List[str]:
        return self.structured_interpretation.prohibitions

    @property
    def conditions(self) -> List[str]:
        return self.structured_interpretation.conditions

    @property
    def triggers(self) -> List[str]:
        return self.structured_interpretation.triggers

    @property
    def deadlines(self) -> List[str]:
        return self.structured_interpretation.deadlines

    @property
    def monetary_values(self) -> List[str]:
        return self.structured_interpretation.monetary_values

    @property
    def penalties(self) -> List[str]:
        return self.structured_interpretation.penalties

    @property
    def termination_conditions(self) -> List[str]:
        return self.structured_interpretation.termination_conditions

    @property
    def jurisdiction(self) -> Optional[str]:
        return self.structured_interpretation.jurisdiction

    @property
    def governing_law(self) -> Optional[str]:
        return self.structured_interpretation.governing_law

    @property
    def arbitration(self) -> Optional[str]:
        return self.structured_interpretation.arbitration

    @property
    def confidentiality(self) -> Optional[str]:
        return self.structured_interpretation.confidentiality

    @property
    def indemnity(self) -> Optional[str]:
        return self.structured_interpretation.indemnity

    @property
    def liability(self) -> Optional[str]:
        return self.structured_interpretation.liability

    @property
    def intellectual_property(self) -> Optional[str]:
        return self.structured_interpretation.intellectual_property

    @property
    def renewal(self) -> Optional[str]:
        return self.structured_interpretation.renewal

    @property
    def dispute_resolution(self) -> Optional[str]:
        return self.structured_interpretation.dispute_resolution

    @property
    def privacy_data_terms(self) -> Optional[str]:
        return self.structured_interpretation.privacy_data_terms

    def to_full_dict(self) -> Dict[str, Any]:
        """Produce a comprehensive flattened dictionary containing both top-level and semantic fields."""
        base = self.model_dump()
        base.update(
            {
                "parties_affected": self.parties_affected,
                "obligations": self.obligations,
                "rights": self.rights,
                "prohibitions": self.prohibitions,
                "conditions": self.conditions,
                "triggers": self.triggers,
                "deadlines": self.deadlines,
                "monetary_values": self.monetary_values,
                "penalties": self.penalties,
                "termination_conditions": self.termination_conditions,
                "jurisdiction": self.jurisdiction,
                "governing_law": self.governing_law,
                "arbitration": self.arbitration,
                "confidentiality": self.confidentiality,
                "indemnity": self.indemnity,
                "liability": self.liability,
                "intellectual_property": self.intellectual_property,
                "renewal": self.renewal,
                "dispute_resolution": self.dispute_resolution,
                "privacy_data_terms": self.privacy_data_terms,
            }
        )
        return base
